name: deploy vue project
on:
  push:
      branches:
        - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Install Dependencies
        run: npm install
        working-directory: ./frontend

      - name: Build
        run: npm run build
        working-directory: ./frontend

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: 'ap-northeast-1'
          role-to-assume: 'arn:aws:iam::448533058664:role/github-actions-s3-deploy'

      - name: Deploy
        run: aws s3 cp --recursive --region ap-northeast-1 dist/ s3://subretu-vue-webhost
        working-directory: ./frontend
